[versions]
agp = "7.3.1"
lifecycle = "2.5.1"
room = "2.4.3"

[libraries]
activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.6.1" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.1" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
core = { module = "androidx.core:core-ktx", version = "1.9.0" }
gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
multidex = { module = "androidx.multidex:multidex", version = "2.0.1" }
paging = { module = "androidx.paging:paging-runtime-ktx", version = "3.1.1" }
palette = { module = "androidx.palette:palette", version = "1.0.0" }
preference = { module = "androidx.preference:preference", version = "1.2.0" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.2.1" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
startup = { module = "androidx.startup:startup-runtime", version = "1.1.1" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.1.0" }

[bundles]
lifecycle = ["lifecycle-runtime", "lifecycle-viewmodel"]
room = ["room-runtime", "room-ktx"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }