[versions]
coil = "2.2.2"
exoplayer = "2.18.1"
kotlinpoet = "1.16.0"
retrofit = "2.10.0"
therouter = "1.3.0"

[libraries]
alicloud-analysis = { module = "com.aliyun.ams:alicloud-android-man", version = "1.2.7" }
alicloud-feedback = { module = "com.aliyun.ams:alicloud-android-feedback", version = "3.4.0" }
alicloud-update = { module = "com.taobao.android:update-main", version = "1.1.14-open" }

apache-commons-net = { module = "commons-net:commons-net", version = "3.9.0" }

github-banner = { module = "io.github.youth5201314:banner", version = "2.2.2" }
github-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
github-coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }
github-jsoup = { module = "org.jsoup:jsoup", version = "1.15.3" }
github-keyboardpanel = { module = "com.github.albfernandez:juniversalchardet", version = "2.4.0" }
github-nanohttpd = { module = "org.nanohttpd:nanohttpd", version = "2.3.1" }
github-smbj = { module = "com.hierynomus:smbj", version = "0.10.0" }
github-dcerpc = { module = "com.rapid7.client:dcerpc", version = "0.10.0" }
github-router-apt = { group = "cn.therouter", name = "apt", version.ref = "therouter" }
github-router = { group = "cn.therouter", name = "router", version.ref = "therouter" }

google-exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
google-exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
google-exoplayer-dash = { module = "com.google.android.exoplayer:exoplayer-dash", version.ref = "exoplayer" }
google-exoplayer-hls = { module = "com.google.android.exoplayer:exoplayer-hls", version.ref = "exoplayer" }
google-exoplayer-rtmp = { module = "com.google.android.exoplayer:extension-rtmp", version.ref = "exoplayer" }
google-exoplayer-smoothstreaming = { module = "com.google.android.exoplayer:exoplayer-smoothstreaming", version.ref = "exoplayer" }
google-material = { module = "com.google.android.material:material", version = "1.8.0-alpha01" }

huawei-scan = { module = "com.huawei.hms:scan", version = "1.3.1.300" }

square-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.10" }
square-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
square-retrofit-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
square-kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
square-kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }

tencent-bugly = { module = "com.tencent.bugly:crashreport", version = "4.1.9" }
tencent-mmkv = { module = "com.tencent:mmkv-static", version = "1.2.14" }

videolan-vlc = { module = "org.videolan.android:libvlc-all", version = "4.0.0-eap9" }

[bundles]
coil = ["github-coil", "github-coil-video"]
exoplayer = [
    "google-exoplayer", "google-exoplayer-core", "google-exoplayer-dash", "google-exoplayer-hls",
    "google-exoplayer-rtmp", "google-exoplayer-smoothstreaming"
]
retrofit = ["square-retrofit", "square-retrofit-serialization"]

[plugins]
router-agp = { id = "cn.therouter.agp8", version.ref = "therouter" }